(function installTrackAExport(scope) {
  const dimensionOrder = [
    ["educational_purpose", "Educational purpose"],
    ["intended_audience", "Intended audience"],
    ["application_setting", "Application setting"],
    ["interactive_narrative_form", "Interactive narrative form"],
    ["interaction_education_relationship", "Interaction → education"],
  ];

  function requireResult(result) {
    if (!result?.run_id || !result?.request || !result?.response) {
      throw new Error("A complete design result is required for export.");
    }
  }

  function inline(value) {
    return String(value ?? "")
      .replace(/\r?\n/gu, " ")
      .replaceAll("|", "\\|")
      .trim();
  }

  function readable(value) {
    return inline(value).replaceAll("_", " ");
  }

  function appendList(lines, items) {
    if (!Array.isArray(items) || items.length === 0) {
      lines.push("- None recorded.");
      return;
    }
    items.forEach((item) => lines.push(`- ${inline(item)}`));
  }

  function createMarkdownExport(result) {
    requireResult(result);
    const { request, response } = result;
    const lines = [
      "# Educational Interactive Narrative Design Export",
      "",
      `- **Run ID:** \`${result.run_id}\``,
      `- **Knowledge snapshot:** \`${response.knowledge_snapshot_id}\``,
      `- **Evidence status:** ${readable(response.evidence_status)}`,
      "",
      "## Design question",
      "",
      inline(request.raw_question),
      "",
      "## Request interpretation",
      "",
      inline(response.request_interpretation),
      "",
      "## Evidence assessment",
      "",
      inline(response.evidence_status_basis?.rationale),
      "",
      "## Retrieved Knowledge Cards",
      "",
    ];

    if (Array.isArray(result.retrieval) && result.retrieval.length > 0) {
      result.retrieval.forEach((item) => {
        const score = Number.isFinite(item.score) ? item.score.toFixed(3) : "not recorded";
        lines.push(`${item.rank}. \`${item.knowledge_id}\` — cosine score ${score}`);
      });
    } else {
      lines.push("No retrieval records were included in this export.");
    }

    response.design_directions.forEach((direction, directionIndex) => {
      lines.push(
        "",
        `## ${directionIndex + 1}. ${inline(direction.title)}`,
        "",
        inline(direction.concept),
        "",
        "### Design dimensions",
        "",
        "| Dimension | Proposed value | Basis |",
        "| --- | --- | --- |",
      );
      dimensionOrder.forEach(([key, label]) => {
        const dimension = direction.design_dimensions[key];
        const basis = (dimension?.basis ?? []).map(readable).join(", ");
        lines.push(`| ${label} | ${inline(dimension?.value)} | ${basis} |`);
      });

      lines.push(
        "",
        "### Interaction mechanism",
        "",
        inline(direction.interaction_mechanism),
        "",
        "### Educational relationship",
        "",
        inline(direction.educational_relationship),
        "",
        "### Knowledge support",
        "",
      );
      direction.knowledge_support.forEach((support) => {
        lines.push(
          `- \`${support.knowledge_id}\` — **${readable(support.match_kind)}:** ${inline(support.use)}`,
        );
      });

      lines.push("", "### Applicability conditions", "");
      appendList(lines, direction.applicability_conditions);
      lines.push("", "### Transfer assumptions", "");
      appendList(lines, direction.transfer_assumptions);
      lines.push("", "### Risks", "");
      appendList(lines, direction.risks);
    });

    lines.push("", "## Limitations", "");
    appendList(lines, response.limitations);
    lines.push("", "## Questions for the next design pass", "");
    appendList(lines, response.follow_up_questions);
    lines.push(
      "",
      "---",
      "",
      "Generated by the local Track A Educational Interactive Narrative Design Helper. Creator-described educational intent is not evidence of learning effectiveness.",
    );

    return {
      fileName: `${result.run_id}-educational-design.md`,
      mimeType: "text/markdown;charset=utf-8",
      content: `${lines.join("\n")}\n`,
    };
  }

  function createJsonExport(result) {
    requireResult(result);
    return {
      fileName: `${result.run_id}-educational-design.json`,
      mimeType: "application/json;charset=utf-8",
      content: `${JSON.stringify(result, null, 2)}\n`,
    };
  }

  scope.TrackAExport = Object.freeze({ createMarkdownExport, createJsonExport });
})(globalThis);
